[tool.poetry]
name = "summarization"
version = "0.1.0"
description = "summarization FastAPI test"
authors = ["eenzeenee <lililio0170@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
fastapi = "^0.89.1"
pytest = "^7.2.1"
torch = "^1.13.1"
transformer-in-transformer = "^0.1.2"
kss = "^4.4.0"
sentence-transformers = "^2.2.2"
tqdm = "^4.64.1"
pandas = "^1.5.3"
nltk = "^3.8.1"
mecab = "^0.996.3"
uvicorn = "0.15.0"
streamlit = "1.2.0"
protobuf = "^3.20.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
